name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # o la rama que elijas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Create application-secrets.properties
        run: |
          echo "spring.datasource.url=jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/railway" >> SkyShop/src/main/resources/application-secrets.properties
          echo "spring.datasource.username=${{ secrets.DB_USER }}" >> SkyShop/src/main/resources/application-secrets.properties
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> SkyShop/src/main/resources/application-secrets.properties

      - name: Build with Maven
        run: |
          cd SkyShop
          mvn package

      - name: Deploy to Railway
        run: |
          npx railway up
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
